#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000

#define BOOT_BUTTON_GPIO        (GPIO_NUM_51)

#define AUDIO_I2S_GPIO_MCLK     (GPIO_NUM_13)
#define AUDIO_I2S_GPIO_WS       (GPIO_NUM_10)
#define AUDIO_I2S_GPIO_BCLK     (GPIO_NUM_12)
#define AUDIO_I2S_GPIO_DIN      (GPIO_NUM_11)
#define AUDIO_I2S_GPIO_DOUT     (GPIO_NUM_9)

#define AUDIO_CODEC_PA_PIN       (GPIO_NUM_53)
#define AUDIO_CODEC_I2C_SDA_PIN  (GPIO_NUM_7)
#define AUDIO_CODEC_I2C_SCL_PIN  (GPIO_NUM_8)
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR

#define THERMAL_PRINTER_TYPE            FTP_628MCL101_50MM
#define THERMAL_PRINTER_UART_PORT       (UART_NUM_1)
#define THERMAL_PRINTER_UART_DTR        (GPIO_NUM_46)
#define THERMAL_PRINTER_UART_TXD        (GPIO_NUM_20)
#define THERMAL_PRINTER_UART_RXD        (GPIO_NUM_21)
#define THERMAL_PRINTER_UART_BAUD_RATE  (9600)

#define DISPLAY_WIDTH                   (480)
#define DISPLAY_HEIGHT                  (480)
#define DISPLAY_MIRROR_X    false
#define DISPLAY_MIRROR_Y    false
#define DISPLAY_SWAP_XY     false
#define DISPLAY_OFFSET_X                (0)
#define DISPLAY_OFFSET_Y                (0)

#define QSPI_LCD_H_RES              (480)
#define QSPI_LCD_V_RES              (480)
#define QSPI_LCD_BIT_PER_PIXEL      (16)

#define QSPI_LCD_HOST               (SPI2_HOST)
#define QSPI_PIN_NUM_LCD_DATA0      (GPIO_NUM_23)
#define QSPI_PIN_NUM_LCD_DATA1      (GPIO_NUM_22)
#define QSPI_PIN_NUM_LCD_DATA2      (GPIO_NUM_33)
#define QSPI_PIN_NUM_LCD_DATA3      (GPIO_NUM_27)
#define QSPI_PIN_NUM_LCD_PCLK       (GPIO_NUM_26)
#define QSPI_PIN_NUM_LCD_CS         (GPIO_NUM_2)
#define QSPI_PIN_NUM_LCD_RST        (GPIO_NUM_32)
#define QSPI_PIN_NUM_LCD_WR         (GPIO_NUM_NC)

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_NC
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#endif // _BOARD_CONFIG_H_
